### ISSUE TITLE
Add possibility to split up data in multiple images

### ISSUE THREAD

**Issue by hounaine** [Ofenhed/Steganography#1]
Hi, have you ever thought to put fractal function to a groupe of images (example: 30x30=900) and each image will have a small part of the fractal object to apply. Same fractal object is never applied twice.

**Comment by Ofenhed** [comment]
Hello. I have not. Just making sure I understand you right, the purpose of this would be to evenly split a big file into multiple images?

**Comment by hounaine** [comment]
Hello. Yes. That's the main idea. My exact proposal is the opposite: apply a big file image to many images. 
1. assemble images into one file
2. apply fractal image to that file
3. divide that file to multiple images

https://gregheartsfield.com/fractal-hs/

**Comment by Ofenhed** [comment]
The issues with fractals are that they are predictable, meaning that the image would be much easier to analyse for hidden content. Applying the randomization algorithm over multiple images, however, is an interesting idea. It will have to be a future feature, though, as I have more important functions to add right now.

**Comment by hounaine** [comment]
Yes :) 4 years later 😄
